#
# multi-cancer studies with ~10k+ genes
#

# input / output directories
data_dir: "/data/raw/cbioportal"
out_dir: "/data/packages/cbioportal/10k"

# minimum number of studies a gene must be present in to be included?
filtering:
  genes:
    min_studies: 2

subsampling:
  patients: 1.0  # combined gene-patient matrix

# options for summary report generation
summary:
  # number of entries to show in summary tables
  table_max_rows: 50

  # minimum ratio of studies gene must be measured in to be included in
  # summary report tables
  min_gene_coverage_ratio: 0.4

  # number of cancer-specific result sections to include; cancer types are ranked according to the
  # number of studies they are present in, and cancer-specfic gene rankings are shown for the top
  # "N" cancer types
  num_cancer_specific_results: 10

# studies to include; this is a subset of the "curated" study list + genie
studies: [
  "metastatic_solid_tumors_mich_2017",
  "mixed_allen_2018",
  "mixed_pipseq_2017",
  "pancan_pcawg_2020",
  "pediatric_dkfz_2017",
  "pog570_bcgsc_2020",
  "pptc_2019"
]

cancer_types: [
  "Acute myeloid leukemia",
  "Adenosarcoma",
  "Adrenal Tumor",
  "Adrenocortical carcinoma",
  "Adrenocortical Carcinoma",
  "Ampullary Cancer",
  "Anal Cancer",
  "Appendiceal Cancer",
  "B-Lymphoblastic Leukemia/Lymphoma",
  "Bladder Cancer",
  "Bone Cancer",
  "Bowel Cancer, NOS",
  "Brain Cancer",
  "Breast Cancer",
  "Breast Sarcoma",
  "Cancer of Unknown Primary",
  "Cervical Cancer",
  "Choroid Plexus Tumor",
  "CNS Cancer",
  "Colorectal Cancer",
  "Cutaneous malignancy of hair matrix cells",
  "Diffuse Glioma",
  "Embryonal Tumor",
  "Encapsulated Glioma",
  "Endometrial Cancer",
  "Ependymomal Tumor",
  "Esophagogastric Cancer",
  "Essential Thrombocythemia",
  "Fibrosarcoma",
  "Gastrointestinal Neuroendocrine Tumor",
  "Gastrointestinal Stromal Tumor",
  "Germ Cell Tumor",
  "Glioblastoma",
  "Glioma",
  "Head and Neck Cancer",
  "Head and Neck Cancer, NOS",
  "Hepatobiliary Cancer",
  "Hodgkin Lymphoma-like PTLD",
  "Intraductal Papillary Mucinous Neoplasm",
  "Leukemia",
  "Liver Tumor",
  "Lung Cancer",
  "Lung Cancer, NOS",
  "Lymphoid Neoplasm",
  "Mastocytosis",
  "Mature B-cell lymphoma",
  "Mature B-Cell Neoplasms",
  "Mature T and NK Neoplasms",
  "Medulloblastoma",
  "Melanoma",
  "Mesothelioma",
  "Miscellaneous Neuroepithelial Tumor",
  "Mucinous Adenocarcinoma Lymph Node",
  "Myelodysplastic/Myeloproliferative Neoplasms",
  "Nerve Sheath Tumor",
  "Nested stromal epithelial tumor of the liver",
  "Non-Germinomatous Germ Cell Tumor",
  "Non-Hodgkin Lymphoma",
  "Non-Seminomatous Germ Cell Tumor",
  "Non-Small Cell Lung Cancer",
  "Other",
  "Ovarian Cancer",
  "Ovarian Germ Cell Tumor",
  "Ovarian/Fallopian Tube Cancer, NOS",
  "Pancreatic Cancer",
  "Penile Cancer",
  "Peripheral Nervous System",
  "Pineal Tumor",
  "Posttransplant Lymphoproliferative Disorders",
  "Prostate Cancer",
  "Prostate Cancer, NOS",
  "Renal cancer",
  "Renal Cell Carcinoma",
  "Retinoblastoma",
  "Salivary Gland Cancer",
  "Salivary Gland-Type Tumor of the Lung",
  "Sellar Tumor",
  "Sex Cord Stromal Tumor",
  "Skin Cancer, Non-Melanoma",
  "Small Bowel Cancer",
  "Small Cell Lung Cancer",
  "Soft Tissue Sarcoma",
  "Soft Tissue Tumor",
  "T-Lymphoblastic Leukemia/Lymphoma",
  "Teratoma with Malignant Transformation",
  "Thymic Tumor",
  "Thyroid Cancer",
  "Uterine Endometrioid Carcinoma",
  "Uterine Sarcoma",
  "Vaginal Cancer",
  "Wilms Tumor"
]
