# input / output directories
data_dir: "/data/raw/cbioportal"
out_dir: "/data/packages/cbioportal/full"

# minimum ratio of studies a gene must be present in to be included
filtering:
  genes:
    min_studies_ratio: 0.05

subsampling:
  patients: 0.15  # combined gene-patient matrix

# clustering options
clustering:
  cancer:
    gene_min_mutations: 1000
    cancer_min_mutations: 10000
    random_seed: 0
    k: 2
  gene:
    gene_min_mutations: 1000
    cancer_min_mutations: 10000
    random_seed: 0
    k: 10

# options for summary report generation
summary:
  # number of entries to show in summary tables
  table_max_rows: 50

  # minimum ratio of studies gene must be measured in to be included in
  # summary report tables
  min_gene_coverage_ratio: 0.05

  # minimum ratio of studies including a specific cancer that a gene must be measured in to be
  # included in cancer-specific summary report tables
  min_gene_coverage_ratio_specific: 0.15

  # number of cancer-specific result sections to include; cancer types are ranked according to the
  # number of studies they are present in, and cancer-specfic gene rankings are shown for the top
  # "N" cancer types
  num_cancer_specific_results: 10

#
# excluding pre-cancer / other studies without a specified cancer type field for now:
# 
# blca_bcan_hcrn_2022
# brca_hta9_htan_2022
# brca_cptac_2020
# crc_hta11_htan_2021
# hcc_meric_2021
# mds_iwg_2022
# mixed_selpercatinib_2020
# mng_utoronto_2021
# prad_msk_mdanderson_2023
# prostate_pcbm_swiss_2019
# ucec_ccr_msk_2022
# ucec_ccr_cfdna_msk_2022
# cscc_ucsf_2021
#

#
# exluding due to other formating issues:
# 
# ccrcc_utokyo_2013
# 

# 
# excluding due to lack of patient-level data:
# 
# bcc_unige_2016
# chol_jhu_2013
# chol_tcga_pan_can_atlas_2018
# cllsll_icgc_2011
# ctcl_columbia_2015
# ccrcc_irc_2014
# ccrcc_utokyo_2013
# hcc_msk_venturaa_2018
# lcll_broad_2013
# lgsoc_mapk_msk_2022
# luad_tsp
# mbl_broad_2012
# mcl_idibips_2013
# mng_utoronto_2021
# mpn_cimr_2013
# nsclc_unito_2016
# sarc_mskcc
# ucec_ccr_cfdna_msk_2022
# ucec_ccr_msk_2022
# utuc_igbmc_2021
# utuc_mskcc_2015
#
 
# studies to include; this is a subset of the "curated" study list + genie
studies: [
  "genie",
  "acc_tcga_pan_can_atlas_2018",
  "ampca_bcm_2016",
  "biliary_tract_summit_2022",
  "gbc_shanghai_2014",
  "chol_icgc_2017",
  "chol_nccs_2013",
  "chol_nus_2012",
  "ihch_ismms_2015",
  "ihch_smmu_2014",
  "bladder_columbia_msk_2018",
  "blca_mskcc_solit_2014",
  "blca_mskcc_solit_2012",
  "blca_bgi",
  "blca_dfarber_mskcc_2014",
  "blca_tcga_pan_can_atlas_2018",
  "blca_cornell_2016",
  "utuc_cornell_baylor_mdacc_2019",
  "utuc_msk_2019",
  "es_iocurie_2014",
  "es_dfarber_broad_2014",
  "coadread_dfci_2016",
  "coadread_genentech",
  "coadread_tcga_pan_can_atlas_2018",
  "coadread_mskcc",
  "coadread_cass_2020",
  "crc_nigerian_2020",
  "coad_caseccc_2015",
  "coad_cptac_2019",
  "coad_silu_2022",
  "bfn_duke_nus_2015",
  "brca_metabric",
  "brca_mskcc_2019",
  "brca_smc_2018",
  "brca_bccrc",
  "brca_broad",
  "brca_sanger",
  "brca_tcga_pan_can_atlas_2018",
  "brca_dfci_2020",
  "brca_igr_2015",
  "brca_mbcproject_wagle_2017",
  "brca_fuscc_2020",
  "acbc_mskcc_2015",
  "brain_cptac_2020",
  "lgg_tcga_pan_can_atlas_2018",
  "difg_glass_2019",
  "glioma_msk_2018",
  "lgg_ucsf_2014",
  "gbm_cptac_2021",
  "gbm_columbia_2019",
  "gbm_tcga_pan_can_atlas_2018",
  "mbl_dkfz_2017",
  "mbl_pcgp",
  "mbl_sickkids_2016",
  "cesc_tcga_pan_can_atlas_2018",
  "escc_icgc",
  "escc_ucla_2014",
  "egc_tmucih_2015",
  "esca_broad",
  "esca_tcga_pan_can_atlas_2018",
  "stad_oncosg_2018",
  "stad_pfizer_uhongkong",
  "stad_tcga_pan_can_atlas_2018",
  "stad_utokyo",
  "um_qimr_2016",
  "uvm_tcga_pan_can_atlas_2018",
  "hnsc_broad",
  "hnsc_jhu",
  "hnsc_tcga_pan_can_atlas_2018",
  "hnsc_mdanderson_2013",
  "npc_nusingapore",
  "acyc_fmi_2014",
  "acyc_jhu_2016",
  "acyc_mda_2015",
  "acyc_mskcc_2013",
  "acyc_sanger_2013",
  "acc_2019",
  "ccrcc_dfci_2019",
  "kirc_bgi",
  "kirc_tcga_pan_can_atlas_2018",
  "kich_tcga_pan_can_atlas_2018",
  "kirp_tcga_pan_can_atlas_2018",
  "nccrcc_genentech_2014",
  "urcc_mskcc_2016",
  "rt_target_2018_pub",
  "mrt_bcgsc_2016",
  "wt_target_2018_pub",
  "liad_inserm_fr_2014",
  "hcc_clca_2024",
  "hcc_inserm_fr_2015",
  "lihc_amc_prv",
  "lihc_riken",
  "lihc_tcga_pan_can_atlas_2018",
  "hccihch_pku_2019",
  "lung_smc_2016",
  "sclc_jhu",
  "sclc_ucologne_2015",
  "sclc_cancercell_gardner_2017",
  "nsclc_mskcc_2018",
  "nsclc_tracerx_2017",
  "luad_broad",
  "luad_cptac_2020",
  "luad_oncosg_2020",
  "luad_tcga_pan_can_atlas_2018",
  "lung_nci_2022",
  "lusc_cptac_2021",
  "lusc_tcga_pan_can_atlas_2018",
  "all_stjude_2016",
  "all_phase2_target_2018_pub",
  "cll_broad_2015",
  "cll_broad_2022",
  "cll_iuopa_2015",
  "dlbcl_dfci_2018",
  "dlbcl_duke_2017",
  "dlbc_tcga_pan_can_atlas_2018",
  "nhl_bcgsc_2013",
  "mm_broad",
  "nhl_bcgsc_2011",
  "pcnsl_mayo_2015",
  "mnm_washu_2016",
  "aml_ohsu_2022",
  "aml_ohsu_2018",
  "laml_tcga_pan_can_atlas_2018",
  "aml_target_2018_pub",
  "histiocytosis_cobi_msk_2019",
  "mds_tokyo_2011",
  "pan_origimed_2020",
  "msk_chord_2024",
  "msk_impact_2017",
  "mixed_allen_2018",
  "metastatic_solid_tumors_mich_2017",
  "pog570_bcgsc_2020",
  "pancan_pcawg_2020",
  "pediatric_dkfz_2017",
  "mixed_pipseq_2017",
  "pptc_2019",
  "summit_2018",
  "ov_tcga_pan_can_atlas_2018",
  "scco_mskcc",
  "paac_jhu_2014",
  "pact_jhu_2011",
  "paad_qcmg_uq_2016",
  "paad_tcga_pan_can_atlas_2018",
  "paad_utsw_2015",
  "paad_cptac_2021",
  "panet_shanghai_2013",
  "panet_jhu_2011",
  "panet_arcnet_2017",
  "mpnst_mskcc",
  "nbl_amc_2012",
  "nbl_ucologne_2015",
  "nbl_target_2018_pub",
  "meso_tcga_pan_can_atlas_2018",
  "plmeso_nyu_2015",
  "prostate_dkfz_2018",
  "prad_msk_2019",
  "mpcproject_broad_2021",
  "prad_mich",
  "prad_su2c_2019",
  "nepc_wcm_2016",
  "prad_broad",
  "prad_fhcrc",
  "prad_mskcc",
  "prad_eururol_2017",
  "prad_tcga_pan_can_atlas_2018",
  "prad_mskcc_cheny1_organoids_2014",
  "cscc_dfarber_2015",
  "cscc_hgsc_bcm_2014",
  "mel_tsam_liang_2017",
  "mel_dfci_2019",
  "mel_ucla_2016",
  "skcm_mskcc_2014",
  "skcm_dfci_2015",
  "skcm_vanderbilt_mskcc_2015",
  "skcm_broad",
  "skcm_tcga_pan_can_atlas_2018",
  "skcm_yale",
  "skcm_broad_brafresist_2012",
  "desm_broad_2015",
  "pcpg_tcga_pan_can_atlas_2018",
  "sarc_tcga_pan_can_atlas_2018",
  "sarcoma_msk_2022",
  "angs_painter_2020",
  "angs_project_painter_2018",
  "rms_nih_2014",
  "stmyec_wcm_2022",
  "tgct_tcga_pan_can_atlas_2018",
  "tet_nci_2014",
  "thym_tcga_pan_can_atlas_2018",
  "thca_tcga_pan_can_atlas_2018",
  "ucec_cptac_2020",
  "ucec_tcga_pan_can_atlas_2018",
  "ucs_jhu_2014",
  "ucs_tcga_pan_can_atlas_2018",
  "uccc_nih_2017",
  "vsc_cuk_2018"
]
